<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.yL2oC5x' shared service.

return $this->privates['.service_locator.yL2oC5x'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\BookController::delete' => ['privates', '.service_locator.PbXwDqA', 'get_ServiceLocator_PbXwDqAService.php', true],
    'App\\Controller\\BookController::edit' => ['privates', '.service_locator.PbXwDqA', 'get_ServiceLocator_PbXwDqAService.php', true],
    'App\\Controller\\BookController::index' => ['privates', '.service_locator.gIcf5jF', 'get_ServiceLocator_GIcf5jFService.php', true],
    'App\\Controller\\BookController::show' => ['privates', '.service_locator.PbXwDqA', 'get_ServiceLocator_PbXwDqAService.php', true],
    'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true],
    'App\\Controller\\UserController::delete' => ['privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true],
    'App\\Controller\\UserController::edit' => ['privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true],
    'App\\Controller\\UserController::index' => ['privates', '.service_locator.JkextnA', 'get_ServiceLocator_JkextnAService.php', true],
    'App\\Controller\\UserController::show' => ['privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true],
    'App\\Controller\\BookController:delete' => ['privates', '.service_locator.PbXwDqA', 'get_ServiceLocator_PbXwDqAService.php', true],
    'App\\Controller\\BookController:edit' => ['privates', '.service_locator.PbXwDqA', 'get_ServiceLocator_PbXwDqAService.php', true],
    'App\\Controller\\BookController:index' => ['privates', '.service_locator.gIcf5jF', 'get_ServiceLocator_GIcf5jFService.php', true],
    'App\\Controller\\BookController:show' => ['privates', '.service_locator.PbXwDqA', 'get_ServiceLocator_PbXwDqAService.php', true],
    'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true],
    'App\\Controller\\UserController:delete' => ['privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true],
    'App\\Controller\\UserController:edit' => ['privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true],
    'App\\Controller\\UserController:index' => ['privates', '.service_locator.JkextnA', 'get_ServiceLocator_JkextnAService.php', true],
    'App\\Controller\\UserController:show' => ['privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true],
]);
