<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerY89WsfR\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerY89WsfR/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerY89WsfR.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerY89WsfR\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerY89WsfR\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Y89WsfR',
    'container.build_id' => '5eae82aa',
    'container.build_time' => 1555341552,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerY89WsfR');
