<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTnAL6xx\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTnAL6xx/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTnAL6xx.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTnAL6xx\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerTnAL6xx\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'TnAL6xx',
    'container.build_id' => '64f3dc37',
    'container.build_time' => 1554717214,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTnAL6xx');
