<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCVZJ1bD\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCVZJ1bD/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCVZJ1bD.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCVZJ1bD\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerCVZJ1bD\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'CVZJ1bD',
    'container.build_id' => '1fc93d85',
    'container.build_time' => 1555343310,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCVZJ1bD');
